/**
 * Export the historical seed for reference, without modifying curated data.
 * Run: node scripts/emit-seed.mjs [--out <new-directory-outside-data>]
 * Default destination: a new xiangsheng-historical-seed-* system temp directory.
 * This historical fixture is not a replacement for the maintained data catalog.
 */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const usage = 'Usage: node scripts/emit-seed.mjs [--out <new-directory-outside-data>]\nExports the historical seed for reference. Curated data remains in data/; existing directories are never overwritten.';
const args = process.argv.slice(2);
if (args.length === 1 && args[0] === '--help') {
  console.log(usage);
  process.exit(0);
}
if (args.length !== 0 && (args.length !== 2 || args[0] !== '--out' || args[1].startsWith('--'))) {
  console.error(usage);
  process.exit(1);
}

function createExportDirectory() {
  const requested = args.length === 0
    ? path.join(os.tmpdir(), 'xiangsheng-historical-seed-')
    : path.resolve(args[1]);
  // Resolve the existing parent so a symlink cannot direct the export into data/.
  const parent = fs.realpathSync(path.dirname(requested));
  const destination = path.join(parent, path.basename(requested));
  const dataDirectory = fs.realpathSync(path.join(root, 'data'));
  const relative = path.relative(dataDirectory, destination);
  if (relative === '' || (relative !== '..' && !relative.startsWith(`..${path.sep}`) && !path.isAbsolute(relative))) {
    throw new Error('Historical seed exports cannot be written inside data/. Choose a new directory outside data/.');
  }
  if (args.length === 0) return fs.mkdtempSync(destination);
  // Exclusive creation refuses existing directories/files, including symlinks.
  fs.mkdirSync(destination);
  return destination;
}

const W = ['src-wiki-lineage'];

function p(partial) {
  return {
    nameHant: undefined,
    aliases: [],
    birthYear: null,
    deathYear: null,
    portrait: null,
    portraitKind: 'placeholder',
    disputed: false,
    notes: [],
    works: [],
    sources: W,
    ...partial,
  };
}

const people = [
  p({
    id: 'zhang-sanlu',
    name: '张三禄',
    generation: null,
    generationIndex: 1,
    floruit: '清咸同年间',
    school: '起源',
    bio: '有记载较早的相声艺人。《江湖丛谈》称其为相声发始创艺人之一，其后分朱、阿、沈三派。与朱绍文等是否直系师承尚待考证。',
    works: ['暗春', '明春'],
    disputed: true,
    notes: ['第一代说法较为通行，直系师承有争议。'],
  }),
  p({
    id: 'zhu-shaowen',
    name: '朱绍文',
    aliases: ['穷不怕'],
    generation: null,
    generationIndex: 2,
    birthYear: 1829,
    deathYear: 1903,
    school: '北京朱派',
    bio: '号穷不怕，相声界多尊为开山祖师。以白沙撒字、说唱莲花落入相声，开北京街头明地传统。',
    works: ['白沙撒字', '莲花落'],
  }),
  p({
    id: 'a-yantao',
    name: '阿彦涛',
    generation: null,
    generationIndex: 2,
    floruit: '清同光年间',
    school: '阿派',
    bio: '早期相声三大派之一阿派代表。文献记载其传人有恩绪、高文奎等，与张三禄的直系关系仍有讨论。',
    disputed: true,
  }),
  p({
    id: 'shen-chunhe',
    name: '沈春和',
    generation: null,
    generationIndex: 2,
    floruit: '清同光年间',
    school: '沈派',
    bio: '早期相声三大派之沈派代表。传人包括魏崑治、冯崑治等，是京津地场的重要源头之一。',
    disputed: true,
  }),
  p({
    id: 'xu-youlu',
    name: '徐有禄',
    aliases: ['徐长福'],
    generation: null,
    generationIndex: 3,
    school: '北京朱派',
    bio: '朱绍文「四庭柱」之一，艺名徐有禄，谱表亦作徐长福。下传焦德海、刘德智等「德」字辈名家。',
  }),
  p({
    id: 'fan-youyuan',
    name: '范有缘',
    aliases: ['范长立'],
    generation: null,
    generationIndex: 3,
    school: '北京朱派',
    bio: '朱绍文门下，传周德山、郭瑞林等，是连接开山一代与「德」字辈的关键支脉。',
  }),
  p({
    id: 'fu-yougen',
    name: '富有根',
    aliases: ['富桂祯'],
    generation: null,
    generationIndex: 3,
    school: '北京朱派',
    bio: '朱绍文门下「四庭柱」之一。传裕德隆、范瑞亭等，相声八德中的裕德隆即出其门。',
  }),
  p({
    id: 'en-xu',
    name: '恩绪',
    generation: null,
    generationIndex: 3,
    school: '阿派',
    bio: '阿彦涛弟子。门下李德钖、李德祥、张德泉等，是「德」字辈能见度很高的一支。',
  }),
  p({
    id: 'feng-kunzhi',
    name: '冯崑治',
    generation: null,
    generationIndex: 3,
    school: '沈派',
    bio: '沈春和传人。下传高德明、高德亮等，北京地场「德」字辈多路从此分出。',
  }),
  p({
    id: 'jiao-dehai',
    name: '焦德海',
    generation: '德',
    generationIndex: 4,
    birthYear: 1878,
    deathYear: 1935,
    school: '北京',
    bio: '相声八德之一。徐有禄（徐长福）弟子，门长张寿臣，并传朱阔泉、常连安等，是近代相声谱系的枢纽。',
    works: ['论捧逗', '开场小唱'],
  }),
  p({
    id: 'zhou-deshan',
    name: '周德山',
    aliases: ['周蛤蟆'],
    generation: '德',
    generationIndex: 4,
    school: '天津',
    bio: '范有缘弟子，相声八德之一。马三立、连秀全等出其门，天津寿字辈的重要源头。',
    works: ['架子活'],
  }),
  p({
    id: 'ma-delu',
    name: '马德禄',
    generation: '德',
    generationIndex: 4,
    birthYear: 1882,
    deathYear: 1933,
    school: '天津',
    bio: '春长隆弟子，相声八德之一，马三立之父。以倒口、贯口见长，天津卫「马家」艺术由此起。',
    works: ['吃元宵'],
  }),
  p({
    id: 'liu-dezhi',
    name: '刘德智',
    generation: '德',
    generationIndex: 4,
    school: '北京',
    bio: '徐长福弟子，相声八德之一。郭启儒出其门，是侯派捧哏传统的上源。',
  }),
  p({
    id: 'yu-delong',
    name: '裕德隆',
    generation: '德',
    generationIndex: 4,
    school: '北京',
    bio: '富有根弟子，相声八德之一。门下王兆麟等，是「德」字辈北京地场的代表人物。',
  }),
  p({
    id: 'li-dexi',
    name: '李德钖',
    aliases: ['李德锡', '万人迷'],
    generation: '德',
    generationIndex: 4,
    birthYear: 1881,
    deathYear: 1923,
    school: '北京',
    bio: '恩绪弟子，艺名万人迷，相声八德之一。以摹仿、倒口著称，对后辈「文」气滑稽影响很大。',
    works: ['卖五器'],
  }),
  p({
    id: 'gao-deliang',
    name: '高德亮',
    generation: '德',
    generationIndex: 4,
    school: '北京',
    bio: '冯崑治弟子。传高凤山。维基注释指出此支或自高德亮起即有「自降一辈」的说法，文献不足，本库加争议标记。',
    disputed: true,
    notes: ['高德亮—高凤山—石富宽—于谦一支部辈有多种说法。'],
  }),
  p({
    id: 'gao-deming',
    name: '高德明',
    generation: '德',
    generationIndex: 4,
    school: '北京',
    bio: '冯崑治弟子，与高德亮同门。北京地场「高」姓德字辈之一。',
  }),
  p({
    id: 'guo-ruilin',
    name: '郭瑞林',
    generation: '德',
    generationIndex: 4,
    school: '北京',
    bio: '范有缘弟子。传侯一尘、谭伯如等，是侯门与宝字辈若干支的上源。',
  }),
  p({
    id: 'lu-dejun',
    name: '卢德俊',
    generation: '德',
    generationIndex: 4,
    school: '北京',
    bio: '徐长福弟子。传赵霭如、陈雨亭等，王世臣一脉由此而出。',
  }),
  p({
    id: 'zhu-kuoquan',
    name: '朱阔泉',
    aliases: ['羊倌朱', '大面包'],
    generation: '寿',
    generationIndex: 5,
    birthYear: 1900,
    deathYear: 1940,
    school: '北京',
    bio: '满族，焦德海弟子，第五代寿字辈。早年收养侯宝林后收为徒弟，并传王凤山、李宝麒等。把莲花落手法更多带进相声。',
    works: ['数来宝', '莲花落'],
    sources: ['src-wiki-lineage', 'src-wiki-zhu-kuoquan'],
  }),
  p({
    id: 'zhang-shouchen',
    name: '张寿臣',
    generation: '寿',
    generationIndex: 5,
    birthYear: 1899,
    deathYear: 1970,
    school: '天津',
    bio: '焦德海门长，寿字辈代表。门下常宝堃、刘宝瑞等，是把「宝」字辈叫响的关键师傅。曾拟「德寿立仁义」，后通行「德寿宝文明」。',
    works: ['文章会', '地理图'],
    sources: ['src-wiki-lineage', 'src-zhihu-generation'],
  }),
  p({
    id: 'ma-sanli',
    name: '马三立',
    aliases: ['马桂福'],
    generation: '寿',
    generationIndex: 5,
    birthYear: 1914,
    deathYear: 2003,
    school: '天津',
    bio: '周德山弟子，马德禄之子。以「贯口」与冷面见长，是天津卫寿字辈最广为人知的代表。对照路径以此为轴。',
    works: ['开粥厂', '买猴', '偏方'],
    sources: ['src-wiki-lineage', 'src-wiki-ma-sanli'],
  }),
  p({
    id: 'chang-lianan',
    name: '常连安',
    generation: '寿',
    generationIndex: 5,
    birthYear: 1899,
    deathYear: 1966,
    school: '北京常家',
    bio: '焦德海弟子，常氏相声开枝的关键人物。其子常宝堃等成名于宝字辈；谱表亦记其传高元钧。',
  }),
  p({
    id: 'hou-yichen',
    name: '侯一尘',
    generation: '寿',
    generationIndex: 5,
    school: '北京',
    bio: '郭瑞林弟子。传连春仲、常宝霖等，与宝字辈常氏、侯氏多有交叉。',
  }),
  p({
    id: 'guo-qiru',
    name: '郭启儒',
    generation: '寿',
    generationIndex: 5,
    birthYear: 1900,
    deathYear: 1969,
    school: '北京',
    bio: '刘德智弟子。长期为侯宝林捧哏，是广播时代对口相声的典范捧哏。马季学艺时亦曾向其问艺。',
    works: ['夜行记（捧哏）', '戏剧杂谈（捧哏）'],
  }),
  p({
    id: 'gao-fengshan',
    name: '高凤山',
    generation: '寿',
    generationIndex: 5,
    birthYear: 1921,
    deathYear: 1995,
    school: '北京',
    bio: '高德亮弟子，以数来宝、快板书名世，亦能相声。传石富宽等。部辈是否与主流「寿」完全对齐，文献有异说。',
    works: ['数来宝', '金针记'],
    disputed: true,
  }),
  p({
    id: 'tan-boru',
    name: '谭伯如',
    generation: '寿',
    generationIndex: 5,
    school: '北京',
    bio: '郭瑞林弟子。陈涌泉、赵世忠出其门，是宝字辈北京「谭门」一支。',
  }),
  p({
    id: 'jiao-shouhai',
    name: '焦寿海',
    generation: '寿',
    generationIndex: 5,
    school: '天津',
    bio: '范瑞亭弟子。门长赵佩茹，并传杨少奎、李润杰等，天津宝字辈重镇。',
  }),
  p({
    id: 'yu-junbo',
    name: '于俊波',
    aliases: ['俊波'],
    generation: '寿',
    generationIndex: 5,
    school: '北京',
    bio: '焦德海弟子，谱表作「俊波」。传郭全宝、白全福等，广播说唱团捧哏一脉多出此门。',
  }),
  p({
    id: 'guo-rongqi',
    name: '郭荣起',
    generation: '寿',
    generationIndex: 5,
    school: '天津',
    bio: '马德禄弟子。传常宝霆、杨少华、谢天顺等，天津宝字辈的另一条主脉。',
  }),
  p({
    id: 'lian-xiuquan',
    name: '连秀全',
    generation: '寿',
    generationIndex: 5,
    school: '天津',
    bio: '周德山弟子，与马三立同门。评书、相声兼能，是天津卫架子的重要一脉。',
  }),
  p({
    id: 'li-shouzeng',
    name: '李寿增',
    generation: '寿',
    generationIndex: 5,
    school: '济南 / 京津',
    bio: '焦德海弟子。传孙少林等，把相声带到济南等地场，是寿字辈跨城传播的代表。',
  }),
  p({
    id: 'chen-yuting',
    name: '陈雨亭',
    generation: '寿',
    generationIndex: 5,
    school: '北京',
    bio: '卢德俊弟子。王世臣出其门，下连刘洪沂、李伟建等文字辈、明字辈。',
  }),
  p({
    id: 'hou-baolin',
    name: '侯宝林',
    generation: '宝',
    generationIndex: 6,
    birthYear: 1917,
    deathYear: 1993,
    school: '北京侯派',
    bio: '朱阔泉弟子（早年被其收养）。把相声带入剧场与广播，强调文学性与人物，是二十世纪最广为人知的宝字辈。',
    works: ['夜行记', '戏剧杂谈', '改行', '关公战秦琼'],
    sources: ['src-wiki-lineage', 'src-wiki-hou-baolin'],
    notes: ['学艺过程中亦得郭启儒等前辈熏陶；责任师承以朱阔泉—侯宝林为主。'],
  }),
  p({
    id: 'chang-baokun',
    name: '常宝堃',
    aliases: ['小蘑菇', '常立桐'],
    generation: '宝',
    generationIndex: 6,
    birthYear: 1922,
    deathYear: 1951,
    school: '天津常家',
    bio: '张寿臣弟子，常连安长子。本名响过艺名，「宝」字辈多因此约定俗成。抗美援朝演出中牺牲。',
    works: ['牙粉袋', '卖估衣'],
  }),
  p({
    id: 'liu-baorui',
    name: '刘宝瑞',
    aliases: ['刘立棠'],
    generation: '宝',
    generationIndex: 6,
    birthYear: 1915,
    deathYear: 1968,
    school: '北京 / 天津',
    bio: '张寿臣弟子，单口大王。唐杰忠、殷文硕等出其门。马季入团时也曾向其问艺。',
    works: ['日遭三险', '假行家', '珍珠翡翠白玉汤'],
  }),
  p({
    id: 'ma-zhiming',
    name: '马志明',
    generation: '宝',
    generationIndex: 6,
    birthYear: 1947,
    school: '天津马家',
    bio: '马三立之子。维基师承表将其列于朱阔泉门下，故本库按谱记边，并加注家庭与师承的双重关系。',
    works: ['纠纷', '卖挂票'],
    disputed: true,
    notes: ['与马三立为父子；正式拜师边依维基表记为朱阔泉。'],
  }),
  p({
    id: 'chang-baohua',
    name: '常宝华',
    generation: '宝',
    generationIndex: 6,
    birthYear: 1930,
    deathYear: 2018,
    school: '天津常家',
    bio: '马三立弟子，常氏宝字辈。传侯耀华、牛群等，并长期担任相声组织与创作工作。',
    works: ['帽子工厂'],
  }),
  p({
    id: 'chang-baoting',
    name: '常宝霆',
    generation: '宝',
    generationIndex: 6,
    birthYear: 1929,
    deathYear: 2018,
    school: '天津常家',
    bio: '郭荣起弟子，常连安之子。与白全福等长期合作，是常氏在宝字辈的另一支。',
    works: ['卖布头'],
  }),
  p({
    id: 'chang-baofeng',
    name: '常宝丰',
    generation: '宝',
    generationIndex: 6,
    school: '天津常家',
    bio: '马三立弟子，常氏宝字辈之一。谱表所记传人较少，是对照常门完整性的节点。',
  }),
  p({
    id: 'guo-quanbao',
    name: '郭全宝',
    generation: '宝',
    generationIndex: 6,
    birthYear: 1922,
    deathYear: 2004,
    school: '北京',
    bio: '于俊波弟子。中央广播说唱团名捧哏，与侯宝林、马季长期合作。',
    works: ['武松打虎（捧哏）'],
  }),
  p({
    id: 'wang-fengshan',
    name: '王凤山',
    generation: '宝',
    generationIndex: 6,
    school: '北京',
    bio: '朱阔泉弟子，与侯宝林同门。下传金文声等，是朱门宝字辈除侯派之外的一条支脉。',
  }),
  p({
    id: 'yang-shaohua',
    name: '杨少华',
    generation: '宝',
    generationIndex: 6,
    birthYear: 1940,
    deathYear: 2021,
    school: '天津',
    bio: '郭荣起弟子。与子杨议等在当代舞台活跃，是天津宝字辈通向当代观众的桥梁。',
    works: ['五味俱全'],
  }),
  p({
    id: 'chen-yongquan',
    name: '陈涌泉',
    generation: '宝',
    generationIndex: 6,
    school: '北京',
    bio: '谭伯如弟子。其父陈子贞为德字辈，本人因拜寿字辈而属宝字辈，常被用来说明「跟师不跟父」。',
    sources: ['src-wiki-lineage', 'src-baike-generation'],
  }),
  p({
    id: 'zhao-shizhong',
    name: '赵世忠',
    generation: '宝',
    generationIndex: 6,
    school: '北京',
    bio: '谭伯如弟子，与陈涌泉同门。北京宝字辈舞台的重要捧逗。',
  }),
  p({
    id: 'shi-fuquan',
    name: '石富宽',
    generation: '宝',
    generationIndex: 6,
    birthYear: 1949,
    school: '北京',
    bio: '高凤山弟子。于谦、孙越、侯震出其门。此支部辈在维基注释中有「自降一辈」异说。',
    disputed: true,
  }),
  p({
    id: 'zhao-peiru',
    name: '赵佩茹',
    aliases: ['赵宝琛'],
    generation: '宝',
    generationIndex: 6,
    birthYear: 1914,
    deathYear: 1973,
    school: '天津',
    bio: '焦寿海门长，常与常宝堃合作。侯耀文、李伯祥、高英培、常贵田等文字辈多出其门。',
  }),
  p({
    id: 'wang-changyou',
    name: '王长友',
    generation: '宝',
    generationIndex: 6,
    school: '北京',
    bio: '赵霭如弟子。传赵振铎等，李金斗一脉的上源。',
  }),
  p({
    id: 'yan-xiaoru',
    name: '阎笑儒',
    generation: '宝',
    generationIndex: 6,
    school: '天津',
    bio: '马三立弟子，「笑」字科名。是马三立对照路径上的重要传人节点。',
  }),
  p({
    id: 'gao-yuankun',
    name: '高元钧',
    generation: '宝',
    generationIndex: 6,
    birthYear: 1916,
    deathYear: 1993,
    school: '快板 / 相声',
    bio: '常连安弟子。以山东快书名世，谱表亦列于相声师承。传李立山等。',
    works: ['武松传'],
  }),
  p({
    id: 'tong-dafang',
    name: '佟大方',
    generation: '宝',
    generationIndex: 6,
    school: '北京',
    bio: '张寿臣弟子。张文顺出其门，是通往当代德云社史叙述中「张文顺」一环的谱上节点。',
  }),
  p({
    id: 'wang-shichen',
    name: '王世臣',
    generation: '宝',
    generationIndex: 6,
    school: '北京',
    bio: '陈雨亭弟子。刘洪沂、李文山等出其门，北京文字辈的一条主脉。',
  }),
  p({
    id: 'zhao-ailu',
    name: '赵霭如',
    generation: '寿',
    generationIndex: 5,
    school: '北京',
    bio: '卢德俊弟子。王长友出其门，下连赵振铎、李金斗。',
  }),
  p({
    id: 'ban-degui',
    name: '班德贵',
    generation: '宝',
    generationIndex: 6,
    school: '天津',
    bio: '马三立弟子。范振钰出其门，是马门通向文字辈的一条边。',
  }),
  p({
    id: 'ma-ji',
    name: '马季',
    aliases: ['马树槐'],
    generation: '文',
    generationIndex: 7,
    birthYear: 1934,
    deathYear: 2006,
    school: '北京侯派',
    bio: '侯宝林责任弟子，亦曾向刘宝瑞、郭全宝、郭启儒问艺。新中国广播相声的代表，门下姜昆、冯巩、赵炎等明字辈。',
    works: ['登山英雄赞', '画像', '找舅舅', '宇宙牌香烟'],
    sources: ['src-wiki-lineage', 'src-wiki-ma-ji'],
    notes: ['多师问艺，师徒关系曾有处世难度的自述；本库主边取侯宝林。'],
  }),
  p({
    id: 'su-wenmao',
    name: '苏文茂',
    aliases: ['苏仲仁'],
    generation: '文',
    generationIndex: 7,
    birthYear: 1929,
    deathYear: 2015,
    school: '天津',
    bio: '常宝堃弟子。坚持用本名，「文」字辈因此叫响。文雅贯口的代表。',
    works: ['论捧逗', '买猴（整理演出）'],
    sources: ['src-wiki-lineage', 'src-zhihu-generation'],
  }),
  p({
    id: 'hou-yaowen',
    name: '侯耀文',
    generation: '文',
    generationIndex: 7,
    birthYear: 1948,
    deathYear: 2007,
    school: '北京侯派',
    bio: '侯宝林之子，谱表记为赵佩茹弟子。传郭德纲、奇志、陈寒柏等。是默认路径通向当代的关键节点。',
    works: ['京九演义', '糖醋活鱼'],
    notes: ['家庭传承与正式拜师表并不等同，本库以维基师承表为准。'],
  }),
  p({
    id: 'zhao-zhenduo',
    name: '赵振铎',
    generation: '文',
    generationIndex: 7,
    birthYear: 1936,
    deathYear: 2021,
    school: '北京',
    bio: '王长友弟子。与赵世忠长期合作，李金斗出其门。',
    works: ['武松打虎'],
  }),
  p({
    id: 'tang-jiezhong',
    name: '唐杰忠',
    generation: '文',
    generationIndex: 7,
    birthYear: 1932,
    deathYear: 2017,
    school: '北京',
    bio: '刘宝瑞弟子。长期为马季、姜昆等捧哏，是文字辈舞台上辨识度极高的捧哏。',
    works: ['宇宙牌香烟（捧哏）'],
  }),
  p({
    id: 'li-boxiang',
    name: '李伯祥',
    generation: '文',
    generationIndex: 7,
    birthYear: 1938,
    school: '天津',
    bio: '赵佩茹弟子。戴志诚等出其门，天津文字辈的代表之一。',
    works: ['吃饺子'],
  }),
  p({
    id: 'gao-yingpei',
    name: '高英培',
    generation: '文',
    generationIndex: 7,
    birthYear: 1928,
    deathYear: 2006,
    school: '天津',
    bio: '赵佩茹弟子。以市井人物与《钓鱼》等作品闻名，范振钰常与其合作。',
    works: ['钓鱼', '一仆二主'],
  }),
  p({
    id: 'ding-guangquan',
    name: '丁广泉',
    generation: '文',
    generationIndex: 7,
    birthYear: 1944,
    deathYear: 2022,
    school: '北京侯派',
    bio: '侯宝林弟子。以教授外国学员相声著称，门下连春建及多位国际学生。',
    works: ['洋相声'],
  }),
  p({
    id: 'shi-shengjie',
    name: '师胜杰',
    generation: '文',
    generationIndex: 7,
    birthYear: 1953,
    deathYear: 2014,
    school: '北京侯派',
    bio: '侯宝林弟子，与马季并称侯门当代重要传人。李菁等出其门。',
    works: ['幽默与友情'],
  }),
  p({
    id: 'yin-wenshuo',
    name: '殷文硕',
    generation: '文',
    generationIndex: 7,
    school: '北京',
    bio: '刘宝瑞弟子。1978–1982 年系统整理《相声师承关系总表》，是本开源谱系最重要的行业文献来源之一。',
    sources: ['src-wiki-lineage', 'src-baike-lineage-table'],
  }),
  p({
    id: 'wu-zhaonan',
    name: '吴兆南',
    generation: '文',
    generationIndex: 7,
    birthYear: 1929,
    deathYear: 2018,
    school: '台湾 / 侯派',
    bio: '侯宝林弟子，把相声带到台湾与海外。郎祖筠、侯冠群等出其门。',
    works: ['吴兆南相声剧场'],
  }),
  p({
    id: 'hou-yaohua',
    name: '侯耀华',
    generation: '文',
    generationIndex: 7,
    birthYear: 1946,
    school: '北京',
    bio: '常宝华弟子，侯宝林次子。影视与相声两栖，何云伟等出其门。',
  }),
  p({
    id: 'niu-qun',
    name: '牛群',
    generation: '文',
    generationIndex: 7,
    birthYear: 1954,
    school: '北京',
    bio: '常宝华弟子。1990 年代与冯巩合作「牛群冯巩」对口，后从政、摄影，舞台作品仍常被提及。',
    works: ['点子公司'],
  }),
  p({
    id: 'li-wenhua',
    name: '李文华',
    generation: '宝',
    generationIndex: 6,
    birthYear: 1927,
    deathYear: 2009,
    school: '北京 / 天津',
    bio: '马三立弟子。长期为姜昆捧哏，《虎口遐想》等作品的固定搭档。辈分上属宝字辈，舞台高峰却在姜昆时期。',
    works: ['如此照相（捧哏）', '虎口遐想（捧哏）'],
  }),
  p({
    id: 'zhang-wenshun',
    name: '张文顺',
    generation: '文',
    generationIndex: 7,
    birthYear: 1946,
    deathYear: 2017,
    school: '北京',
    bio: '佟大方弟子。当代叙述中常被提及为郭德纲问艺对象之一，并给德云社弟子起「云鹤九霄」科名。',
    notes: ['与郭德纲的师承在公开叙述中有问艺/合作成分，主拜师边仍以侯耀文为准。'],
  }),
  p({
    id: 'jia-jiguang',
    name: '贾冀光',
    aliases: ['贾继光'],
    generation: '文',
    generationIndex: 7,
    school: '北京侯派',
    bio: '侯宝林弟子。谱表或作贾继光。侯门文字辈的一支。',
  }),
  p({
    id: 'hao-aimin',
    name: '郝爱民',
    generation: '文',
    generationIndex: 7,
    school: '北京侯派',
    bio: '侯宝林弟子。部队与舞台相声皆有影响，是侯门文字辈的代表之一。',
  }),
  p({
    id: 'huang-tieliang',
    name: '黄铁良',
    generation: '文',
    generationIndex: 7,
    school: '天津 / 侯派',
    bio: '侯宝林弟子。长期在天津发展，是侯派在津门的文字辈节点。',
  }),
  p({
    id: 'yang-ziyang',
    name: '杨紫阳',
    generation: '文',
    generationIndex: 7,
    school: '北京侯派',
    bio: '侯宝林弟子。仇小豹、王迅等出其门。',
  }),
  p({
    id: 'li-lishan',
    name: '李立山',
    generation: '文',
    generationIndex: 7,
    school: '快板 / 相声',
    bio: '高元钧弟子。贾旭明等出其门，连接快板书谱系与相声明字辈。',
  }),
  p({
    id: 'liu-hongyi',
    name: '刘洪沂',
    generation: '文',
    generationIndex: 7,
    school: '北京',
    bio: '王世臣弟子。李伟建出其门，北京广播相声文字辈的一条线。',
  }),
  p({
    id: 'fan-zhenyu',
    name: '范振钰',
    generation: '文',
    generationIndex: 7,
    birthYear: 1935,
    deathYear: 2021,
    school: '天津',
    bio: '班德贵弟子。长期与高英培合作，是文字辈捧哏的代表。',
    works: ['钓鱼（捧哏）'],
  }),
  p({
    id: 'chang-guitian',
    name: '常贵田',
    generation: '文',
    generationIndex: 7,
    birthYear: 1942,
    school: '天津常家',
    bio: '赵佩茹弟子，常宝堃之子。常氏由宝字辈过渡到文字辈的家庭与师承交叉点。',
  }),
  p({
    id: 'jiang-kun',
    name: '姜昆',
    generation: '明',
    generationIndex: 8,
    birthYear: 1950,
    school: '北京马季门',
    bio: '马季弟子，明字辈代表。与李文华合作《如此照相》《虎口遐想》。默认路径「传人」的第一站。',
    works: ['如此照相', '虎口遐想', '电梯奇遇'],
    sources: ['src-wiki-lineage', 'src-wiki-jiang-kun'],
  }),
  p({
    id: 'feng-gong',
    name: '冯巩',
    generation: '明',
    generationIndex: 8,
    birthYear: 1957,
    school: '北京马季门',
    bio: '马季弟子。春晚常客，门下贾玲等。默认路径「传人」之一。',
    works: ['小小气功师', '点子公司'],
  }),
  p({
    id: 'zhao-yan',
    name: '赵炎',
    generation: '明',
    generationIndex: 8,
    birthYear: 1948,
    school: '北京马季门',
    bio: '马季早期弟子之一，与刘伟长期合作，是马门明字辈的中坚。',
    works: ['虎口遐想（早期合作）'],
  }),
  p({
    id: 'liu-wei',
    name: '刘伟',
    generation: '明',
    generationIndex: 8,
    birthYear: 1957,
    school: '北京马季门',
    bio: '马季弟子，常与赵炎搭档。注意谱上另有师胜杰门下同名「刘伟」，本条专指马季此徒。',
  }),
  p({
    id: 'xiao-lin',
    name: '笑林',
    generation: '明',
    generationIndex: 8,
    birthYear: 1957,
    deathYear: 2020,
    school: '北京马季门',
    bio: '马季弟子，与李国盛等合作。马门明字辈中以俊朗捧逗风格为人熟知。',
  }),
  p({
    id: 'wang-qianxiang',
    name: '王谦祥',
    generation: '明',
    generationIndex: 8,
    school: '北京马季门',
    bio: '马季弟子，常与李增瑞合作。李寅飞等出其门。',
  }),
  p({
    id: 'li-zengrui',
    name: '李增瑞',
    generation: '明',
    generationIndex: 8,
    school: '北京马季门',
    bio: '马季弟子。李丁出其门，是马门通向第九代的一条边。',
  }),
  p({
    id: 'han-lancheng',
    name: '韩兰成',
    aliases: ['韩兰城'],
    generation: '明',
    generationIndex: 8,
    school: '北京马季门',
    bio: '马季弟子。谱表或作韩兰城。范军、小飞等出其门。',
  }),
  p({
    id: 'huang-hong',
    name: '黄宏',
    generation: '明',
    generationIndex: 8,
    birthYear: 1960,
    school: '北京马季门',
    bio: '马季弟子。以小品名世，谱表仍列于马季相声门墙。',
    works: ['超生游击队'],
  }),
  p({
    id: 'guo-degang',
    name: '郭德纲',
    generation: '明',
    generationIndex: 8,
    birthYear: 1973,
    school: '北京德云社',
    bio: '维基表记为侯耀文弟子。创办德云社，以传统本子复兴著称。公开叙述中亦强调张文顺等问艺，故师承边标记争议。',
    works: ['论捧逗', '我是黑社会', '西征梦'],
    sources: ['src-wiki-lineage', 'src-wiki-guo-degang'],
    disputed: true,
    notes: ['主边：侯耀文。张文顺等为问艺/科名来源，不作第二条主师边。'],
  }),
  p({
    id: 'yu-qian',
    name: '于谦',
    generation: '文',
    generationIndex: 7,
    birthYear: 1969,
    school: '北京',
    bio: '石富宽弟子。与郭德纲长期合作，但按字辈表为文字辈，并非郭德纲弟子。郭麒麟出其门。',
    works: ['我要闹着玩儿（捧哏）'],
    notes: ['舞台搭档不等于师徒；辈分上于谦高于郭德纲一辈。'],
  }),
  p({
    id: 'li-jindou',
    name: '李金斗',
    generation: '明',
    generationIndex: 8,
    birthYear: 1947,
    school: '北京',
    bio: '赵振铎弟子。大兵、刘颖等出其门，是北京明字辈通向第九代的一条宽边。',
    works: ['武松打虎'],
  }),
  p({
    id: 'qi-zhi',
    name: '奇志',
    generation: '明',
    generationIndex: 8,
    birthYear: 1964,
    school: '湖南 / 侯耀文门',
    bio: '侯耀文弟子。与大兵长期合作，南派对口的代表。',
    works: ['托儿'],
  }),
  p({
    id: 'dai-zhicheng',
    name: '戴志诚',
    generation: '明',
    generationIndex: 8,
    birthYear: 1957,
    school: '天津 / 北京',
    bio: '李伯祥弟子。常为姜昆等捧哏，是明字辈舞台上的重要捧哏。',
  }),
  p({
    id: 'li-weijian',
    name: '李伟建',
    generation: '明',
    generationIndex: 8,
    school: '北京',
    bio: '刘洪沂弟子。广播相声与剧场演出并重的明字辈。',
  }),
  p({
    id: 'sun-yue',
    name: '孙越',
    generation: '明',
    generationIndex: 8,
    birthYear: 1972,
    school: '北京',
    bio: '维基表分别列于石富宽与赵小林门下。本库主边取石富宽，并标记双重记载。',
    disputed: true,
    notes: ['另见赵小林门下同名记载。'],
  }),
  p({
    id: 'li-jing',
    name: '李菁',
    generation: '明',
    generationIndex: 8,
    birthYear: 1978,
    school: '北京',
    bio: '师胜杰弟子。曾为德云社主要演员，后独立。是侯门通向明字辈的一条边。',
  }),
  p({
    id: 'ju-hao',
    name: '句号',
    generation: null,
    generationIndex: 9,
    birthYear: 1967,
    school: '北京姜昆门',
    bio: '姜昆弟子。第九代暂无通行字辈。影视与相声两栖。',
  }),
  p({
    id: 'da-shan',
    name: '大山',
    aliases: ['Mark Rowswell'],
    generation: null,
    generationIndex: 9,
    birthYear: 1965,
    school: '北京姜昆门',
    bio: '姜昆弟子，加拿大籍相声演员。把相声带入跨文化舞台。第九代无字辈。',
    works: ['洋相'],
  }),
  p({
    id: 'chen-hanbai',
    name: '陈寒柏',
    generation: '明',
    generationIndex: 8,
    school: '北京侯耀文门',
    bio: '侯耀文弟子。部队与春晚舞台皆有作品，是侯门明字辈之一。',
  }),
  p({
    id: 'yue-yunpeng',
    name: '岳云鹏',
    generation: null,
    generationIndex: 9,
    birthYear: 1985,
    school: '德云社云字科',
    bio: '郭德纲「云」字科学员。第九代无传统字辈，科名「云」是社内科班，不是「德寿宝文明」的续字。',
    works: ['我是歌手', '论捧逗'],
    notes: ['科名 ≠ 传统字辈。'],
  }),
  p({
    id: 'da-bing',
    name: '大兵',
    generation: null,
    generationIndex: 9,
    birthYear: 1969,
    school: '湖南 / 李金斗门',
    bio: '李金斗弟子。与奇志长期合作。第九代。',
    works: ['托儿'],
  }),
  p({
    id: 'guo-qilin',
    name: '郭麒麟',
    generation: null,
    generationIndex: 9,
    birthYear: 1996,
    school: '北京',
    bio: '于谦弟子，郭德纲之子。谱上按拜师边归于谦，不按家庭自动降辈。',
    notes: ['父子与师徒分记。'],
  }),
  p({
    id: 'jia-ling',
    name: '贾玲',
    generation: null,
    generationIndex: 9,
    birthYear: 1982,
    school: '冯巩门',
    bio: '冯巩弟子。以小品、影视名世，谱表仍列于冯巩相声门墙。本库只列作品标题，不提供音视频。',
    works: ['好家伙'],
  }),
  p({
    id: 'luan-yunping',
    name: '栾云平',
    generation: null,
    generationIndex: 9,
    birthYear: 1982,
    school: '德云社云字科',
    bio: '郭德纲云字科。德云社舞台的主要演员与管理成员之一。',
  }),
  p({
    id: 'cao-heyang',
    name: '曹鹤阳',
    generation: null,
    generationIndex: 9,
    school: '德云社鹤字科',
    bio: '郭德纲门下鹤字科相声演员。曹鹤阳与曹云金是不同人物。',
  }),
  p({
    id: 'li-ding',
    name: '李丁',
    generation: null,
    generationIndex: 9,
    school: '北京马季再传',
    bio: '李增瑞弟子。马季门下再传的第九代演员。',
  }),
  p({
    id: 'zhang-yunlei',
    name: '张云雷',
    generation: null,
    generationIndex: 9,
    birthYear: 1992,
    school: '德云社云字科',
    bio: '郭德纲云字科。以太平歌词与传统本子见长。第九代无传统字辈。',
    works: ['太平歌词'],
  }),
];

const pairs = [
  ['zhang-sanlu', 'zhu-shaowen', true, '与朱绍文是否直系尚待考证。'],
  ['zhang-sanlu', 'a-yantao', true, '三大派源头关系待考。'],
  ['zhang-sanlu', 'shen-chunhe', true, '三大派源头关系待考。'],
  ['zhu-shaowen', 'xu-youlu'],
  ['zhu-shaowen', 'fan-youyuan'],
  ['zhu-shaowen', 'fu-yougen'],
  ['a-yantao', 'en-xu'],
  ['shen-chunhe', 'feng-kunzhi'],
  ['xu-youlu', 'jiao-dehai'],
  ['xu-youlu', 'liu-dezhi'],
  ['xu-youlu', 'lu-dejun'],
  ['fan-youyuan', 'zhou-deshan'],
  ['fan-youyuan', 'guo-ruilin'],
  ['fu-yougen', 'yu-delong'],
  ['en-xu', 'li-dexi'],
  ['feng-kunzhi', 'gao-deliang'],
  ['feng-kunzhi', 'gao-deming'],
  ['jiao-dehai', 'zhu-kuoquan'],
  ['jiao-dehai', 'zhang-shouchen'],
  ['jiao-dehai', 'chang-lianan'],
  ['jiao-dehai', 'yu-junbo'],
  ['jiao-dehai', 'li-shouzeng'],
  ['zhou-deshan', 'ma-sanli'],
  ['zhou-deshan', 'lian-xiuquan'],
  ['liu-dezhi', 'guo-qiru'],
  ['guo-ruilin', 'hou-yichen'],
  ['guo-ruilin', 'tan-boru'],
  ['lu-dejun', 'chen-yuting'],
  ['lu-dejun', 'zhao-ailu'],
  ['gao-deliang', 'gao-fengshan', true, '此支部辈或有自降，文献不足。'],
  ['zhu-kuoquan', 'hou-baolin', false, '早年收养，后正式收徒。'],
  ['zhu-kuoquan', 'wang-fengshan'],
  ['zhu-kuoquan', 'ma-zhiming', true, '马三立之子；谱表记拜朱阔泉。'],
  ['zhang-shouchen', 'chang-baokun'],
  ['zhang-shouchen', 'liu-baorui'],
  ['zhang-shouchen', 'tong-dafang'],
  ['ma-sanli', 'yan-xiaoru'],
  ['ma-sanli', 'chang-baohua'],
  ['ma-sanli', 'chang-baofeng'],
  ['ma-sanli', 'li-wenhua'],
  ['ma-sanli', 'ban-degui'],
  ['chang-lianan', 'gao-yuankun'],
  ['tan-boru', 'chen-yongquan'],
  ['tan-boru', 'zhao-shizhong'],
  ['jiao-shouhai', 'zhao-peiru'],
  ['yu-junbo', 'guo-quanbao'],
  ['guo-rongqi', 'chang-baoting'],
  ['guo-rongqi', 'yang-shaohua'],
  ['ma-delu', 'guo-rongqi'],
  ['gao-fengshan', 'shi-fuquan', true],
  ['zhao-ailu', 'wang-changyou'],
  ['chen-yuting', 'wang-shichen'],
  ['hou-baolin', 'ma-ji'],
  ['hou-baolin', 'shi-shengjie'],
  ['hou-baolin', 'ding-guangquan'],
  ['hou-baolin', 'wu-zhaonan'],
  ['hou-baolin', 'hao-aimin'],
  ['hou-baolin', 'jia-jiguang'],
  ['hou-baolin', 'huang-tieliang'],
  ['hou-baolin', 'yang-ziyang'],
  ['chang-baokun', 'su-wenmao'],
  ['liu-baorui', 'tang-jiezhong'],
  ['liu-baorui', 'yin-wenshuo'],
  ['zhao-peiru', 'hou-yaowen'],
  ['zhao-peiru', 'li-boxiang'],
  ['zhao-peiru', 'gao-yingpei'],
  ['zhao-peiru', 'chang-guitian'],
  ['wang-changyou', 'zhao-zhenduo'],
  ['chang-baohua', 'hou-yaohua'],
  ['chang-baohua', 'niu-qun'],
  ['shi-fuquan', 'yu-qian'],
  ['shi-fuquan', 'sun-yue', true, '亦见赵小林门下记载。'],
  ['gao-yuankun', 'li-lishan'],
  ['tong-dafang', 'zhang-wenshun'],
  ['wang-shichen', 'liu-hongyi'],
  ['ban-degui', 'fan-zhenyu'],
  ['ma-ji', 'jiang-kun'],
  ['ma-ji', 'feng-gong'],
  ['ma-ji', 'zhao-yan'],
  ['ma-ji', 'liu-wei'],
  ['ma-ji', 'xiao-lin'],
  ['ma-ji', 'wang-qianxiang'],
  ['ma-ji', 'li-zengrui'],
  ['ma-ji', 'han-lancheng'],
  ['ma-ji', 'huang-hong'],
  ['hou-yaowen', 'guo-degang', true, '公开叙述中另有张文顺等问艺。'],
  ['hou-yaowen', 'qi-zhi'],
  ['hou-yaowen', 'chen-hanbai'],
  ['zhao-zhenduo', 'li-jindou'],
  ['li-boxiang', 'dai-zhicheng'],
  ['liu-hongyi', 'li-weijian'],
  ['shi-shengjie', 'li-jing'],
  ['jiang-kun', 'ju-hao'],
  ['jiang-kun', 'da-shan'],
  ['feng-gong', 'jia-ling'],
  ['guo-degang', 'yue-yunpeng'],
  ['guo-degang', 'luan-yunping'],
  ['guo-degang', 'cao-heyang'],
  ['guo-degang', 'zhang-yunlei'],
  ['yu-qian', 'guo-qilin'],
  ['li-jindou', 'da-bing'],
  ['li-zengrui', 'li-ding'],
];

const edges = pairs.map(([from, to, disputed = false, note]) => ({
  id: `${from}--${to}`,
  from,
  to,
  type: 'mentor',
  disputed: Boolean(disputed),
  sources: W,
  ...(note ? { note } : {}),
}));

const ids = new Set(people.map((x) => x.id));
const missing = edges.flatMap((e) => [e.from, e.to].filter((id) => !ids.has(id)));
if (missing.length) {
  throw new Error(`Missing people: ${[...new Set(missing)].join(', ')}`);
}

let exportDirectory;
try {
  exportDirectory = createExportDirectory();
} catch (error) {
  console.error(`Seed export refused: ${error.message}\nChoose a new output directory whose parent already exists.\n${usage}`);
  process.exit(1);
}
const peopleDir = path.join(exportDirectory, 'people');
fs.mkdirSync(peopleDir);

for (const person of people) {
  const clean = { ...person };
  if (!clean.nameHant) delete clean.nameHant;
  if (!clean.aliases?.length) delete clean.aliases;
  if (!clean.floruit) delete clean.floruit;
  if (!clean.school) delete clean.school;
  if (!clean.notes?.length) delete clean.notes;
  if (clean.portrait == null) delete clean.portrait;
  if (!clean.disputed) delete clean.disputed;
  if (clean.birthYear == null) delete clean.birthYear;
  if (clean.deathYear == null) delete clean.deathYear;
  fs.writeFileSync(path.join(peopleDir, `${person.id}.json`), `${JSON.stringify(clean, null, 2)}\n`, { flag: 'wx' });
}

fs.writeFileSync(
  path.join(exportDirectory, 'edges.json'),
  `${JSON.stringify({ edges }, null, 2)}\n`,
  { flag: 'wx' },
);

console.log(`Historical seed export: ${exportDirectory}`);
console.log(`people=${people.length} edges=${edges.length}`);
console.log('Reference fixture only; it omits later corrections, people, events, and source additions. Maintain and validate the curated data/ catalog directly.');
